#!/bin/bash

sudo nohup python3 watcher_htx.py -s BTCUSDT > x_htx_BTCUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s ETHUSDT > x_htx_ETHUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s LTCUSDT > x_htx_LTCUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s DOGEUSDT > x_htx_DOGEUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s ICPUSDT > x_htx_ICPUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s XRPUSDT > x_htx_XRPUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s LINKUSDT > x_htx_LINKUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s FTTUSDT > x_htx_FTTUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s DOTUSDT > x_htx_DOTUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s ADAUSDT > x_htx_ADAUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s EOSUSDT > x_htx_EOSUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s BCHUSDT > x_htx_BCHUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s BSVUSDT > x_htx_BSVUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s YFIUSDT > x_htx_YFIUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s UNIUSDT > x_htx_UNIUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s FILUSDT > x_htx_FILUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s SNXUSDT > x_htx_SNXUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s BNBUSDT > x_htx_BNBUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s ETCUSDT > x_htx_ETCUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s THETAUSDT > x_htx_THETAUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s KSMUSDT > x_htx_KSMUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s ATOMUSDT > x_htx_ATOMUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s AAVEUSDT > x_htx_AAVEUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s XLMUSDT > x_htx_XLMUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s SUSHIUSDT > x_htx_SUSHIUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s GRTUSDT > x_htx_GRTUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s 1INCHUSDT > x_htx_1INCHUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s CRVUSDT > x_htx_CRVUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s ALGOUSDT > x_htx_ALGOUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s WAVESUSDT > x_htx_WAVESUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s COMPUSDT > x_htx_COMPUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s XMRUSDT > x_htx_XMRUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s KAVAUSDT > x_htx_KAVAUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s AVAXUSDT > x_htx_AVAXUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s MATICUSDT > x_htx_MATICUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s ARBUSDT > x_htx_ARBUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s WIFUSDT > x_htx_WIFUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s MKRUSDT > x_htx_MKRUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s SANDUSDT > x_htx_SANDUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s MASKUSDT > x_htx_MASKUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s NEARUSDT > x_htx_NEARUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s MANAUSDT > x_htx_MANAUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s WOOUSDT > x_htx_WOOUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s CHZUSDT > x_htx_CHZUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s WLDUSDT > x_htx_WLDUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s AXSUSDT > x_htx_AXSUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s LRCUSDT > x_htx_LRCUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s YGGUSDT > x_htx_YGGUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s COTIUSDT > x_htx_COTIUSDT.out 2>&1 &
sudo nohup python3 watcher_htx.py -s DYDXUSDT > x_htx_DYDXUSDT.out 2>&1 &